# fly.toml app configuration file generated for dark-morning-5976-quiet-dew-225 on 2024-03-07T21:11:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dark-morning-5976-quiet-dew-225'
primary_region = 'mia'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
